#pragma once

//#define SAMPLE_MAIN_CPP
//#define SAMPLE_MAIN_UI_BUTTON_CPP
//#define SAMPLE_MAIN_GL_CUBES_LIGHT_CPP
//#define SAMPLE_MAIN_SIMPLE_TRIANGLES_CPP
//#define SAMPLE_MAIN_SIMPLE_TRIANGLES_TRANSFORM_CPP
//#define SAMPLE_MAIN_SIMPLE_TRIANGLES_CLASS_CPP
//#define SAMPLE_MAIN_SIMPLE_TRIANGLES_CLASS_CAMERA_CPP


//#define SAMPLE_MAIN_GL_TEXT_CPP
//#define SAMPLE_TEXT_PAINTER_CPP
//#define SAMPLE_MAIN_SIMPLE_TRIANGLES_TEXTURE_CPP
//#define SAMPLE_MAIN_UI_TEXTURE_TEXT_BUTTON_CPP

//Audio

#define SAMPLE_MAIN_AUDIO_TEST

// IF_LAB
//#define IF_LAB_MAIN3_CPP
//#define IF_LAB_MAIN33TYPE_CPP
//#define IF_LAB_MAIN4_CPP
//#define IF_LAB_WINAPI_CPP
//#define SIMPLE_TRIANGLES_CLASS_TEXTURE_TEXT_RAW_CPP